/*
 * Team Investment Tool
 * Team Investment Tool
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.clerkvest.api.entity.investment;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import de.clerkvest.api.entity.company.CompanyDTO;
import de.clerkvest.api.implement.service.IServiceEntity;
import org.springframework.hateoas.RepresentationModel;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * InvestInRest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2019-04-26T13:56:04.987Z")
@JsonIgnoreProperties({"invest_id"})
public class InvestDTO extends RepresentationModel<InvestDTO> implements IServiceEntity {
    private Long invest_id = null;

    private Long project_id;

    private Long employee_id;

    private BigDecimal investment = null;

    public InvestDTO() {

    }

    public InvestDTO(Invest investIn) {
        invest_id = investIn.getId();
        project_id = investIn.getProjectId().getId();
        employee_id = investIn.getEmployeeId().getId();
        investment = investIn.getInvestment();
    }

    public InvestDTO investInId(Long investInId) {
        this.invest_id = investInId;
        return this;
    }

    /**
     * Get invest_in_id
     *
     * @return invest_in_id
     **/
    public Long getInvest_in_id() {
        return invest_id;
    }

    public void setInvest_in_id(Long invest_in_id) {
        this.invest_id = invest_in_id;
    }

    public InvestDTO projectId(long projectRestId) {
        this.project_id = projectRestId;
        return this;
    }

    /**
     * Get project_id
     *
     * @return project_id
     **/
    public long getProject_id() {
        return project_id;
    }

    public void setProject_id(Long project_id) {
        this.project_id = project_id;
    }

    public InvestDTO employeeId(Long employeeRestId) {
        this.employee_id = employeeRestId;
        return this;
    }

    /**
     * Get employee_id
     *
     * @return employee_id
     **/
    public long getEmployee_id() {
        return employee_id;
    }

    public void setEmployee_id(Long employee_id) {
        this.employee_id = employee_id;
    }

    public InvestDTO investment(BigDecimal investment) {
        this.investment = investment;
        return this;
    }

    /**
     * Get investment
     *
     * @return investment
     **/
    public BigDecimal getInvestment() {
        return investment;
    }

    public void setInvestment(BigDecimal investment) {
        this.investment = investment;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InvestDTO investDTO = (InvestDTO) o;
        return Objects.equals(this.invest_id, investDTO.invest_id) &&
                Objects.equals(this.project_id, investDTO.project_id) &&
                Objects.equals(this.employee_id, investDTO.employee_id) &&
                Objects.equals(this.investment, investDTO.investment);
    }

    @Override
    public int hashCode() {
        return Objects.hash(invest_id, project_id, employee_id, investment);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InvestInRest {\n");

        sb.append("    invest_in_id: ").append(toIndentedString(invest_id)).append("\n");
        sb.append("    project_id: ").append(toIndentedString(project_id)).append("\n");
        sb.append("    employee_id: ").append(toIndentedString(employee_id)).append("\n");
        sb.append("    investment: ").append(toIndentedString(investment)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public Long getId() {
        return invest_id;
    }

    @Override
    public void setId(Long id) {
        invest_id = id;
    }
}

