name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: joschi/setup-jdk@v1
        with:
          java-version: 'openjdk11'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        continue-on-error: true
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@9fcf5a3
        with:
          args: '{{ github.event.head_commit.message }} has been pushed to {{ EVENT_PAYLOAD.repository.full_name }}.'
